apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.label.name }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: <some certificate>
    # https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/minimize-downtime-during-deployments.md
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
spec:
  rules:
    - host: {{ .Values.host.name }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.label.name }}
              servicePort: {{ .Values.ports.http }}
