apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{  .Values.label.name  }}-stage
  name: {{  .Values.label.name  }}-stage
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{  .Values.ports.http  }}
    name: http
  selector:
    app: {{  .Values.label.name  }}
    # This determines which deployment the service is currently pointing to
    slot: {{ .Values.stagingSlot }}
